server:
  port: 8080
  address: 0.0.0.0 # 추가: 모든 IP에서 접근 허용

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//61.73.18.134:1521/MYXE
    username: sys
    password: Akstp3ckd
    hikari:
      pool-name: HikariPool-Oracle
      data-source-properties:
        internal_logon: SYSDBA
      maximum-pool-size: 5
      connection-test-query: "SELECT 1 FROM DUAL"

      jpa:
        open-in-view: false
        # SYS로는 스키마 변경을 피하는 게 안전
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            format_sql: true
            show_sql: true

    logging:
      level:
        org.hibernate.SQL: debug
