server:
  port: 8080
  address: 0.0.0.0 # 추가: 모든 IP에서 접근 허용

spring:
  # Oracle Database 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@61.73.18.134:1521:MYXE
    username: sys
    password: Akstp3ckd

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update  # Oracle에서는 update 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        # Oracle 특화 설정
        jdbc:
          batch_size: 20
        connection:
          characterEncoding: UTF-8
          useUnicode: true

  # H2 Console 비활성화 (Oracle 사용 시 불필요)
  # h2:
  #   console:
  #     enabled: false